<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->bigIncrements('id');

            $table->string('abbr');
            $table->string('name');
            $table->timestamps();
        });

        $this->seedCountries();
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::seedCountries('countries');
    }

    private function seedCountries(){

        $counties = array(
            ['id' =>1, 'abbr' =>'AF', 'name' => 'Afghanistan'],
            ['id' =>2, 'abbr' =>'AL', 'name' => 'Albania'],
            ['id' =>3, 'abbr' =>'DZ', 'name' => 'Algeria'],
            ['id' =>4, 'abbr' =>'AS', 'name' => 'American Samoa'],
            ['id' =>5, 'abbr' =>'AD', 'name' => 'Andorra'],
            ['id' =>6, 'abbr' =>'AO', 'name' => 'Angola'],
            ['id' =>7, 'abbr' =>'AI', 'name' => 'Anguilla'],
            ['id' =>8, 'abbr' =>'AQ', 'name' => 'Antarctica'],
            ['id' =>9, 'abbr' =>'AG', 'name' => 'Antigua And Barbuda'],
            ['id' =>10, 'abbr' =>'AR', 'name' => 'Argentina'],
            ['id' =>11, 'abbr' =>'AM', 'name' => 'Armenia'],
            ['id' =>12, 'abbr' =>'AW', 'name' => 'Aruba'],
            ['id' =>13, 'abbr' =>'AU', 'name' => 'Australia'],
            ['id' =>14, 'abbr' =>'AT', 'name' => 'Austria'],
            ['id' =>15, 'abbr' =>'AZ', 'name' => 'Azerbaijan'],
            ['id' =>16, 'abbr' =>'BS', 'name' => 'Bahamas'],
            ['id' =>17, 'abbr' =>'BH', 'name' => 'Bahrain'],
            ['id' =>18, 'abbr' =>'BD', 'name' => 'Bangladesh'],
            ['id' =>19, 'abbr' =>'BB', 'name' => 'Barbados'],
            ['id' =>20, 'abbr' =>'BY', 'name' => 'Belarus'],
            ['id' =>21, 'abbr' =>'BE', 'name' => 'Belgium'],
            ['id' =>22, 'abbr' =>'BZ', 'name' => 'Belize'],
            ['id' =>23, 'abbr' =>'BJ', 'name' => 'Benin'],
            ['id' =>24, 'abbr' =>'BM', 'name' => 'Bermuda'],
            ['id' =>25, 'abbr' =>'BT', 'name' => 'Bhutan'],
            ['id' =>26, 'abbr' =>'BO', 'name' => 'Bolivia'],
            ['id' =>27, 'abbr' =>'BA', 'name' => 'Bosnia And Herzegovina'],
            ['id' =>28, 'abbr' =>'BW', 'name' => 'Botswana'],
            ['id' =>29, 'abbr' =>'BV', 'name' => 'Bouvet Island'],
            ['id' =>30, 'abbr' =>'BR', 'name' => 'Brazil'],
            ['id' =>31, 'abbr' =>'IO', 'name' => 'British Indian Ocean Territory'],
            ['id' =>32, 'abbr' =>'BN', 'name' => 'Brunei Darussalam'],
            ['id' =>33, 'abbr' =>'BG', 'name' => 'Bulgaria'],
            ['id' =>34, 'abbr' =>'BF', 'name' => 'Burkina Faso'],
            ['id' =>35, 'abbr' =>'BI', 'name' => 'Burundi'],
            ['id' =>36, 'abbr' =>'KH', 'name' => 'Cambodia'],
            ['id' =>37, 'abbr' =>'CM', 'name' => 'Cameroon'],
            ['id' =>38, 'abbr' =>'CA', 'name' => 'Canada'],
            ['id' =>39, 'abbr' =>'CV', 'name' => 'Cape Verde'],
            ['id' =>40, 'abbr' =>'KY', 'name' => 'Cayman Islands'],
            ['id' =>41, 'abbr' =>'CF', 'name' => 'Central African Republic'],
            ['id' =>42, 'abbr' =>'TD', 'name' => 'Chad'],
            ['id' =>43, 'abbr' =>'CL', 'name' => 'Chile'],
            ['id' =>44, 'abbr' =>'CN', 'name' => 'China'],
            ['id' =>45, 'abbr' =>'CX', 'name' => 'Christmas Island'],
            ['id' =>46, 'abbr' =>'CC', 'name' => 'Cocos (keeling) Islands'],
            ['id' =>47, 'abbr' =>'CO', 'name' => 'Colombia'],
            ['id' =>48, 'abbr' =>'KM', 'name' => 'Comoros'],
            ['id' =>49, 'abbr' =>'CG', 'name' => 'Congo'],
            ['id' =>50, 'abbr' =>'CD', 'name' => 'Congo, The Democratic Republic Of The'],
            ['id' =>51, 'abbr' =>'CK', 'name' => 'Cook Islands'],
            ['id' =>52, 'abbr' =>'CR', 'name' => 'Costa Rica'],
            ['id' =>53, 'abbr' =>'CI', 'name' => 'Cote D\'ivoire'],
            ['id' =>54, 'abbr' =>'HR', 'name' => 'Croatia'],
            ['id' =>55, 'abbr' =>'CU', 'name' => 'Cuba'],
            ['id' =>56, 'abbr' =>'CY', 'name' => 'Cyprus'],
            ['id' =>57, 'abbr' =>'CZ', 'name' => 'Czech Republic'],
            ['id' =>58, 'abbr' =>'DK', 'name' => 'Denmark'],
            ['id' =>59, 'abbr' =>'DJ', 'name' => 'Djibouti'],
            ['id' =>60, 'abbr' =>'DM', 'name' => 'Dominica'],
            ['id' =>61, 'abbr' =>'DO', 'name' => 'Dominican Republic'],
            ['id' =>62, 'abbr' =>'TP', 'name' => 'East Timor'],
            ['id' =>63, 'abbr' =>'EC', 'name' => 'Ecuador'],
            ['id' =>64, 'abbr' =>'EG', 'name' => 'Egypt'],
            ['id' =>65, 'abbr' =>'SV', 'name' => 'El Salvador'],
            ['id' =>66, 'abbr' =>'GQ', 'name' => 'Equatorial Guinea'],
            ['id' =>67, 'abbr' =>'ER', 'name' => 'Eritrea'],
            ['id' =>68, 'abbr' =>'EE', 'name' => 'Estonia'],
            ['id' =>69, 'abbr' =>'ET', 'name' => 'Ethiopia'],
            ['id' =>70, 'abbr' =>'FK', 'name' => 'Falkland Islands (malvinas)'],
            ['id' =>71, 'abbr' =>'FO', 'name' => 'Faroe Islands'],
            ['id' =>72, 'abbr' =>'FJ', 'name' => 'Fiji'],
            ['id' =>73, 'abbr' =>'FI', 'name' => 'Finland'],
            ['id' =>74, 'abbr' =>'FR', 'name' => 'France'],
            ['id' =>75, 'abbr' =>'GF', 'name' => 'French Guiana'],
            ['id' =>76, 'abbr' =>'PF', 'name' => 'French Polynesia'],
            ['id' =>77, 'abbr' =>'TF', 'name' => 'French Southern Territories'],
            ['id' =>78, 'abbr' =>'GA', 'name' => 'Gabon'],
            ['id' =>79, 'abbr' =>'GM', 'name' => 'Gambia'],
            ['id' =>80, 'abbr' =>'GE', 'name' => 'Georgia'],
            ['id' =>81, 'abbr' =>'DE', 'name' => 'Germany'],
            ['id' =>82, 'abbr' =>'GH', 'name' => 'Ghana'],
            ['id' =>83, 'abbr' =>'GI', 'name' => 'Gibraltar'],
            ['id' =>84, 'abbr' =>'GR', 'name' => 'Greece'],
            ['id' =>85, 'abbr' =>'GL', 'name' => 'Greenland'],
            ['id' =>86, 'abbr' =>'GD', 'name' => 'Grenada'],
            ['id' =>87, 'abbr' =>'GP', 'name' => 'Guadeloupe'],
            ['id' =>88, 'abbr' =>'GU', 'name' => 'Guam'],
            ['id' =>89, 'abbr' =>'GT', 'name' => 'Guatemala'],
            ['id' =>90, 'abbr' =>'GN', 'name' => 'Guinea'],
            ['id' =>91, 'abbr' =>'GW', 'name' => 'Guinea-bissau'],
            ['id' =>92, 'abbr' =>'GY', 'name' => 'Guyana'],
            ['id' =>93, 'abbr' =>'HT', 'name' => 'Haiti'],
            ['id' =>94, 'abbr' =>'HM', 'name' => 'Heard Island And Mcdonald Islands'],
            ['id' =>95, 'abbr' =>'VA', 'name' => 'Holy See (vatican City State)'],
            ['id' =>96, 'abbr' =>'HN', 'name' => 'Honduras'],
            ['id' =>97, 'abbr' =>'HK', 'name' => 'Hong Kong'],
            ['id' =>98, 'abbr' =>'HU', 'name' => 'Hungary'],
            ['id' =>99, 'abbr' =>'IS', 'name' => 'Iceland'],
            ['id' =>100, 'abbr' =>'IN', 'name' => 'India'],
            ['id' =>101, 'abbr' =>'ID', 'name' => 'Indonesia'],
            ['id' =>102, 'abbr' =>'IR', 'name' => 'Iran, Islamic Republic Of'],
            ['id' =>103, 'abbr' =>'IQ', 'name' => 'Iraq'],
            ['id' =>104, 'abbr' =>'IE', 'name' => 'Ireland'],
            ['id' =>105, 'abbr' =>'IL', 'name' => 'Israel'],
            ['id' =>106, 'abbr' =>'IT', 'name' => 'Italy'],
            ['id' =>107, 'abbr' =>'JM', 'name' => 'Jamaica'],
            ['id' =>108, 'abbr' =>'JP', 'name' => 'Japan'],
            ['id' =>109, 'abbr' =>'JO', 'name' => 'Jordan'],
            ['id' =>110, 'abbr' =>'KZ', 'name' => 'Kazakstan'],
            ['id' =>111, 'abbr' =>'KE', 'name' => 'Kenya'],
            ['id' =>112, 'abbr' =>'KI', 'name' => 'Kiribati'],
            ['id' =>113, 'abbr' =>'KP', 'name' => 'Korea, Democratic People\'s Republic Of'],
            ['id' =>114, 'abbr' =>'KR', 'name' => 'Korea, Republic Of'],
            ['id' =>115, 'abbr' =>'KV', 'name' => 'Kosovo'],
            ['id' =>116, 'abbr' =>'KW', 'name' => 'Kuwait'],
            ['id' =>117, 'abbr' =>'KG', 'name' => 'Kyrgyzstan'],
            ['id' =>118, 'abbr' =>'LA', 'name' => 'Lao People\'s Democratic Republic'],
            ['id' =>119, 'abbr' =>'LV', 'name' => 'Latvia'],
            ['id' =>120, 'abbr' =>'LB', 'name' => 'Lebanon'],
            ['id' =>121, 'abbr' =>'LS', 'name' => 'Lesotho'],
            ['id' =>122, 'abbr' =>'LR', 'name' => 'Liberia'],
            ['id' =>123, 'abbr' =>'LY', 'name' => 'Libyan Arab Jamahiriya'],
            ['id' =>124, 'abbr' =>'LI', 'name' => 'Liechtenstein'],
            ['id' =>125, 'abbr' =>'LT', 'name' => 'Lithuania'],
            ['id' =>126, 'abbr' =>'LU', 'name' => 'Luxembourg'],
            ['id' =>127, 'abbr' =>'MO', 'name' => 'Macau'],
            ['id' =>128, 'abbr' =>'MK', 'name' => 'Macedonia, The Former Yugoslav Republic Of'],
            ['id' =>129, 'abbr' =>'MG', 'name' => 'Madagascar'],
            ['id' =>130, 'abbr' =>'MW', 'name' => 'Malawi'],
            ['id' =>131, 'abbr' =>'MY', 'name' => 'Malaysia'],
            ['id' =>132, 'abbr' =>'MV', 'name' => 'Maldives'],
            ['id' =>133, 'abbr' =>'ML', 'name' => 'Mali'],
            ['id' =>134, 'abbr' =>'MT', 'name' => 'Malta'],
            ['id' =>135, 'abbr' =>'MH', 'name' => 'Marshall Islands'],
            ['id' =>136, 'abbr' =>'MQ', 'name' => 'Martinique'],
            ['id' =>137, 'abbr' =>'MR', 'name' => 'Mauritania'],
            ['id' =>138, 'abbr' =>'MU', 'name' => 'Mauritius'],
            ['id' =>139, 'abbr' =>'YT', 'name' => 'Mayotte'],
            ['id' =>140, 'abbr' =>'MX', 'name' => 'Mexico'],
            ['id' =>141, 'abbr' =>'FM', 'name' => 'Micronesia, Federated States Of'],
            ['id' =>142, 'abbr' =>'MD', 'name' => 'Moldova, Republic Of'],
            ['id' =>143, 'abbr' =>'MC', 'name' => 'Monaco'],
            ['id' =>144, 'abbr' =>'MN', 'name' => 'Mongolia'],
            ['id' =>145, 'abbr' =>'MS', 'name' => 'Montserrat'],
            ['id' =>146, 'abbr' =>'ME', 'name' => 'Montenegro'],
            ['id' =>147, 'abbr' =>'MA', 'name' => 'Morocco'],
            ['id' =>148, 'abbr' =>'MZ', 'name' => 'Mozambique'],
            ['id' =>149, 'abbr' =>'MM', 'name' => 'Myanmar'],
            ['id' =>150, 'abbr' =>'NA', 'name' => 'Namibia'],
            ['id' =>151, 'abbr' =>'NR', 'name' => 'Nauru'],
            ['id' =>152, 'abbr' =>'NP', 'name' => 'Nepal'],
            ['id' =>153, 'abbr' =>'NL', 'name' => 'Netherlands'],
            ['id' =>154, 'abbr' =>'AN', 'name' => 'Netherlands Antilles'],
            ['id' =>155, 'abbr' =>'NC', 'name' => 'New Caledonia'],
            ['id' =>156, 'abbr' =>'NZ', 'name' => 'New Zealand'],
            ['id' =>157, 'abbr' =>'NI', 'name' => 'Nicaragua'],
            ['id' =>158, 'abbr' =>'NE', 'name' => 'Niger'],
            ['id' =>159, 'abbr' =>'NG', 'name' => 'Nigeria'],
            ['id' =>160, 'abbr' =>'NU', 'name' => 'Niue'],
            ['id' =>161, 'abbr' =>'NF', 'name' => 'Norfolk Island'],
            ['id' =>162, 'abbr' =>'MP', 'name' => 'Northern Mariana Islands'],
            ['id' =>163, 'abbr' =>'NO', 'name' => 'Norway'],
            ['id' =>164, 'abbr' =>'OM', 'name' => 'Oman'],
            ['id' =>165, 'abbr' =>'PK', 'name' => 'Pakistan'],
            ['id' =>166, 'abbr' =>'PW', 'name' => 'Palau'],
            ['id' =>167, 'abbr' =>'PS', 'name' => 'Palestinian Territory, Occupied'],
            ['id' =>168, 'abbr' =>'PA', 'name' => 'Panama'],
            ['id' =>169, 'abbr' =>'PG', 'name' => 'Papua New Guinea'],
            ['id' =>170, 'abbr' =>'PY', 'name' => 'Paraguay'],
            ['id' =>171, 'abbr' =>'PE', 'name' => 'Peru'],
            ['id' =>172, 'abbr' =>'PH', 'name' => 'Philippines'],
            ['id' =>173, 'abbr' =>'PN', 'name' => 'Pitcairn'],
            ['id' =>174, 'abbr' =>'PL', 'name' => 'Poland'],
            ['id' =>175, 'abbr' =>'PT', 'name' => 'Portugal'],
            ['id' =>176, 'abbr' =>'PR', 'name' => 'Puerto Rico'],
            ['id' =>177, 'abbr' =>'QA', 'name' => 'Qatar'],
            ['id' =>178, 'abbr' =>'RE', 'name' => 'Reunion'],
            ['id' =>179, 'abbr' =>'RO', 'name' => 'Romania'],
            ['id' =>180, 'abbr' =>'RU', 'name' => 'Russian Federation'],
            ['id' =>181, 'abbr' =>'RW', 'name' => 'Rwanda'],
            ['id' =>182, 'abbr' =>'SH', 'name' => 'Saint Helena'],
            ['id' =>183, 'abbr' =>'KN', 'name' => 'Saint Kitts And Nevis'],
            ['id' =>184, 'abbr' =>'LC', 'name' => 'Saint Lucia'],
            ['id' =>185, 'abbr' =>'PM', 'name' => 'Saint Pierre And Miquelon'],
            ['id' =>186, 'abbr' =>'VC', 'name' => 'Saint Vincent And The Grenadines'],
            ['id' =>187, 'abbr' =>'WS', 'name' => 'Samoa'],
            ['id' =>188, 'abbr' =>'SM', 'name' => 'San Marino'],
            ['id' =>189, 'abbr' =>'ST', 'name' => 'Sao Tome And Principe'],
            ['id' =>190, 'abbr' =>'SA', 'name' => 'Saudi Arabia'],
            ['id' =>191, 'abbr' =>'SN', 'name' => 'Senegal'],
            ['id' =>192, 'abbr' =>'RS', 'name' => 'Serbia'],
            ['id' =>193, 'abbr' =>'SC', 'name' => 'Seychelles'],
            ['id' =>194, 'abbr' =>'SL', 'name' => 'Sierra Leone'],
            ['id' =>195, 'abbr' =>'SG', 'name' => 'Singapore'],
            ['id' =>196, 'abbr' =>'SK', 'name' => 'Slovakia'],
            ['id' =>197, 'abbr' =>'SI', 'name' => 'Slovenia'],
            ['id' =>198, 'abbr' =>'SB', 'name' => 'Solomon Islands'],
            ['id' =>199, 'abbr' =>'SO', 'name' => 'Somalia'],
            ['id' =>200, 'abbr' =>'ZA', 'name' => 'South Africa'],
            ['id' =>201, 'abbr' =>'GS', 'name' => 'South Georgia And The South Sandwich Islands'],
            ['id' =>202, 'abbr' =>'ES', 'name' => 'Spain'],
            ['id' =>203, 'abbr' =>'LK', 'name' => 'Sri Lanka'],
            ['id' =>204, 'abbr' =>'SD', 'name' => 'Sudan'],
            ['id' =>205, 'abbr' =>'SR', 'name' => 'Suriname'],
            ['id' =>206, 'abbr' =>'SJ', 'name' => 'Svalbard And Jan Mayen'],
            ['id' =>207, 'abbr' =>'SZ', 'name' => 'Swaziland'],
            ['id' =>208, 'abbr' =>'SE', 'name' => 'Sweden'],
            ['id' =>209, 'abbr' =>'CH', 'name' => 'Switzerland'],
            ['id' =>210, 'abbr' =>'SY', 'name' => 'Syrian Arab Republic'],
            ['id' =>211, 'abbr' =>'TW', 'name' => 'Taiwan, Province Of China'],
            ['id' =>212, 'abbr' =>'TJ', 'name' => 'Tajikistan'],
            ['id' =>213, 'abbr' =>'TZ', 'name' => 'Tanzania, United Republic Of'],
            ['id' =>214, 'abbr' =>'TH', 'name' => 'Thailand'],
            ['id' =>215, 'abbr' =>'TG', 'name' => 'Togo'],
            ['id' =>216, 'abbr' =>'TK', 'name' => 'Tokelau'],
            ['id' =>217, 'abbr' =>'TO', 'name' => 'Tonga'],
            ['id' =>218, 'abbr' =>'TT', 'name' => 'Trinidad And Tobago'],
            ['id' =>219, 'abbr' =>'TN', 'name' => 'Tunisia'],
            ['id' =>220, 'abbr' =>'TR', 'name' => 'Turkey'],
            ['id' =>221, 'abbr' =>'TM', 'name' => 'Turkmenistan'],
            ['id' =>222, 'abbr' =>'TC', 'name' => 'Turks And Caicos Islands'],
            ['id' =>223, 'abbr' =>'TV', 'name' => 'Tuvalu'],
            ['id' =>224, 'abbr' =>'UG', 'name' => 'Uganda'],
            ['id' =>225, 'abbr' =>'UA', 'name' => 'Ukraine'],
            ['id' =>226, 'abbr' =>'AE', 'name' => 'United Arab Emirates'],
            ['id' =>227, 'abbr' =>'GB', 'name' => 'United Kingdom'],
            ['id' =>228, 'abbr' =>'US', 'name' => 'United States'],
            ['id' =>229, 'abbr' =>'UM', 'name' => 'United States Minor Outlying Islands'],
            ['id' =>230, 'abbr' =>'UY', 'name' => 'Uruguay'],
            ['id' =>231, 'abbr' =>'UZ', 'name' => 'Uzbekistan'],
            ['id' =>232, 'abbr' =>'VU', 'name' => 'Vanuatu'],
            ['id' =>233, 'abbr' =>'VE', 'name' => 'Venezuela'],
            ['id' =>234, 'abbr' =>'VN', 'name' => 'Viet Nam'],
            ['id' =>235, 'abbr' =>'VG', 'name' => 'Virgin Islands, British'],
            ['id' =>236, 'abbr' =>'VI', 'name' => 'Virgin Islands, U.s.'],
            ['id' =>237, 'abbr' =>'WF', 'name' => 'Wallis And Futuna'],
            ['id' =>238, 'abbr' =>'EH', 'name' => 'Western Sahara'],
            ['id' =>239, 'abbr' =>'YE', 'name' => 'Yemen'],
            ['id' =>240, 'abbr' =>'ZM', 'name' => 'Zambia'],
            ['id' =>241, 'abbr' =>'ZW', 'name' => 'Zimbabwe'],

        );
        DB::table('countries')->insert($counties);

    }
}
